# Generated by Django 5.0.6 on 2024-06-30 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='badge',
            field=models.ForeignKey(blank=True, default='not a prefect', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.badge', verbose_name='Prefect Tittle (if is prefect)'),
        ),
    ]
