# Generated by Django 4.2.15 on 2024-08-16 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='date_admitted',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='dob',
            field=models.DateField(blank=True, default='2020-01-01', null=True, verbose_name='Date of Birth(Y-M-D)'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='relationship',
            field=models.CharField(choices=[('select', 'select'), ('father', 'father'), ('mother', 'mother'), ('sister', 'sister'), ('brother', 'brother'), ('aunt', 'aunt'), ('uncle', 'uncle'), ('other', 'other')], default='select', help_text="Guardian's Relationship With Student", max_length=25),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='student_username',
            field=models.CharField(help_text='Type New Username For Student', max_length=20, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Click The Search Button To Select The New Username If Not Available, ADD New User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student Username'),
        ),
    ]
