# Generated by Django 4.2.15 on 2024-08-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='student_username',
            field=models.CharField(max_length=20, unique=True, verbose_name='StudentID'),
        ),
    ]
