# Generated by Django 5.0.6 on 2024-06-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='student_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('graduated', 'graduated'), ('dropped', 'dropped'), ('expelled', 'expelled'), ('suspended', 'suspended')], default='inactive', max_length=15),
        ),
    ]
