# Generated by Django 4.2.15 on 2024-08-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentdetail_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='date_admitted',
            field=models.DateField(),
        ),
    ]
