# Generated by Django 4.2.15 on 2024-08-14 15:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=150)),
                ('acc_number', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150, verbose_name='Bank Name')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Payment Category',
                'verbose_name_plural': 'Payment Categories',
            },
        ),
        migrations.CreateModel(
            name='PaymentChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('term', models.CharField(blank=True, choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term'), ('Others', 'Others')], max_length=50)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payment_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentcategory')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.session')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid_a', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('payment_date_a', models.DateField()),
                ('other_details_a', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('amount_paid_b', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('payment_date_b', models.DateField(blank=True, null=True)),
                ('other_details_b', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('amount_paid_c', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('payment_date_c', models.DateField(blank=True, null=True)),
                ('other_details_c', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('discount', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='enter in %', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='TOTAL DISCOUNT(if any)')),
                ('confirmed_a', models.BooleanField(default=False)),
                ('confirmed_b', models.BooleanField(default=False)),
                ('confirmed_c', models.BooleanField(default=False)),
                ('payment_updated_date', models.DateField(auto_now_add=True)),
                ('bank_name_a', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_name_a', to='payment.bankdetail')),
                ('bank_name_b', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_name_b', to='payment.bankdetail')),
                ('bank_name_c', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.bankdetail')),
                ('payment_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment_name', to='payment.paymentchart')),
                ('student_detail', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentdetail')),
                ('student_id', models.ForeignKey(default=None, help_text='confirm student username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-student_detail'],
                'unique_together': {('student_detail', 'payment_name')},
            },
        ),
    ]
