# Generated by Django 5.0.6 on 2024-06-22 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='bank_name_b',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_name_b', to='payment.bankdetail'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='bank_name_c',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.bankdetail'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_date_b',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_date_c',
            field=models.DateField(blank=True, null=True),
        ),
    ]
