# Generated by Django 5.0.6 on 2024-06-26 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentdetail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='student_id',
            field=models.ForeignKey(blank=True, default=None, help_text='confirm student username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
