# Generated by Django 5.0.6 on 2024-06-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentdetail_unique_together_and_more'),
        ('students', '0002_alter_studentdetail_student_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentdetail',
            unique_together={('student_detail', 'payment_name')},
        ),
    ]
