# Generated by Django 5.0.6 on 2024-06-22 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Staff Category',
                'verbose_name_plural': 'Staff Categories',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_username', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('select_gender', 'select_gender')], default='select_gender', max_length=20)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('region_origin', models.CharField(choices=[('Select', 'Select'), ('SouthWest', 'SouthWest'), ('SouthEast', 'SouthEast'), ('SouthSouth', 'SouthSouth'), ('NorthWest', 'NorthWest'), ('NorthEast', 'NorthEast'), ('NorthCentral', 'NorthCentral')], default='Select', max_length=20)),
                ('date_employed', models.DateField()),
                ('staff_role', models.CharField(choices=[('form_teacher', 'form_teacher'), ('principal', 'principal'), ('head_teacher', 'head_teacher'), ('admin_officer', 'admin_officer'), ('account_officer', 'account_officer'), ('non_teching', 'non_teaching'), ('others', 'others'), ('select', 'select')], default='select', max_length=20)),
                ('marital_status', models.CharField(choices=[('married', 'married'), ('single', 'single'), ('select', 'select')], default='select', max_length=15)),
                ('phone_home', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(max_length=150)),
                ('year', models.DateField()),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('professional_body', models.CharField(blank=True, max_length=150)),
                ('guarantor_name', models.CharField(blank=True, max_length=150)),
                ('guarantor_phone', models.CharField(blank=True, max_length=150)),
                ('guarantor_address', models.CharField(blank=True, max_length=150)),
                ('guarantor_email', models.CharField(blank=True, max_length=60)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=60)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=15)),
                ('cat_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffcategory')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.classgroup')),
                ('class_in_charge', models.ForeignKey(blank=True, default='no teacher', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='curriculum.standard')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
