# Generated by Django 5.0.6 on 2024-06-25 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('item_location', models.CharField(blank=True, max_length=150)),
                ('date_recorded', models.DateField(default=None)),
                ('date_added', models.DateField(auto_now=True)),
                ('staff_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffprofile')),
            ],
            options={
                'verbose_name': 'Inventory Items',
                'verbose_name_plural': 'Inventory Items',
            },
        ),
    ]
