# Generated by Django 4.2.15 on 2024-08-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(null=True)),
                ('morning_status', models.BooleanField(default=False)),
                ('afternoon_status', models.BooleanField(default=False)),
                ('authorized_sign', models.CharField(default='none', max_length=20)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, default='2023/2024', null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.session')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentdetail')),
            ],
            options={
                'unique_together': {('student_id', 'attendance_date', 'session')},
            },
        ),
    ]
