# Generated by Django 5.0.6 on 2024-06-23 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term'), ('Others', 'Others')], default='First Term', max_length=15)),
                ('attendance_date', models.DateField(null=True)),
                ('morning_status', models.BooleanField(default=False)),
                ('afternoon_status', models.BooleanField(default=False)),
                ('authorized_sign', models.CharField(default='none', max_length=20)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, default='2023/2024', null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.session')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentdetail')),
            ],
            options={
                'unique_together': {('student_id', 'attendance_date', 'session', 'term')},
            },
        ),
    ]
