# Generated by Django 5.0.6 on 2024-07-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('curriculum', '0002_alter_session_term'),
        ('students', '0002_alter_badge_name_alter_studentdetail_badge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student_id', 'attendance_date', 'session')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='term',
        ),
    ]
