# Generated by Django 4.2.15 on 2024-08-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.standard'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffprofile'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentdetail'),
        ),
        migrations.AlterField(
            model_name='attendancetotal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentdetail'),
        ),
        migrations.CreateModel(
            name='Attendance_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(null=True)),
                ('morning_status', models.BooleanField(default=False)),
                ('afternoon_status', models.BooleanField(default=False)),
                ('authorized_sign', models.CharField(default='none', max_length=20)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, default='2023/2024', null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.session')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentdetail')),
            ],
            options={
                'unique_together': {('student_id', 'attendance_date', 'session')},
            },
        ),
    ]
