# Generated by Django 4.2.15 on 2024-08-16 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='DOB',
        ),
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateField(blank=True, default='1998-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.CharField(help_text='Click Search Button To Select Same As Above', max_length=100, primary_key=True, serialize=False, verbose_name='Enter Username Again'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teacher Username'),
        ),
    ]
