# Generated by Django 4.2.15 on 2024-08-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('attendance', '0002_remove_teacher_dob_student_dob_alter_teacher_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='DOB',
        ),
        migrations.AddField(
            model_name='teacher',
            name='staff_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffprofile', verbose_name="Teacher's Detail"),
        ),
    ]
